// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9H6qQ7pP8u79KPKWPyIBruYmcsEh3No',
    appId: '1:539614773659:web:890670dd46f85bfda7a13e',
    messagingSenderId: '539614773659',
    projectId: 'fb-notes-eb910',
    authDomain: 'fb-notes-eb910.firebaseapp.com',
    storageBucket: 'fb-notes-eb910.firebasestorage.app',
    measurementId: 'G-TVC4G0M1MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDux38Kwk6FZmjQXS3qQweO6FIf3hr7wBs',
    appId: '1:539614773659:android:7118f5d8f69e6991a7a13e',
    messagingSenderId: '539614773659',
    projectId: 'fb-notes-eb910',
    storageBucket: 'fb-notes-eb910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-hspzTQC9upOA9kHkvJuWD1ydJ1I_yU',
    appId: '1:539614773659:ios:6e381bdc03ef9ccba7a13e',
    messagingSenderId: '539614773659',
    projectId: 'fb-notes-eb910',
    storageBucket: 'fb-notes-eb910.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-hspzTQC9upOA9kHkvJuWD1ydJ1I_yU',
    appId: '1:539614773659:ios:6e381bdc03ef9ccba7a13e',
    messagingSenderId: '539614773659',
    projectId: 'fb-notes-eb910',
    storageBucket: 'fb-notes-eb910.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp9H6qQ7pP8u79KPKWPyIBruYmcsEh3No',
    appId: '1:539614773659:web:129fccce694dcd23a7a13e',
    messagingSenderId: '539614773659',
    projectId: 'fb-notes-eb910',
    authDomain: 'fb-notes-eb910.firebaseapp.com',
    storageBucket: 'fb-notes-eb910.firebasestorage.app',
    measurementId: 'G-SVQ25VV18J',
  );
}
